/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from "@icp-sdk/core/candid";

export const Id = IDL.Nat;
export const UserRole = IDL.Variant({
  admin: IDL.Null,
  user: IDL.Null,
  guest: IDL.Null,
});
export const Time = IDL.Int;
export const ServiceSlot = IDL.Record({
  service: IDL.Text,
  startTime: IDL.Text,
  sitterId: IDL.Nat,
  endTime: IDL.Text,
  durationMinutes: IDL.Nat,
  ratePerHour: IDL.Nat,
});
export const DayServiceSchedule = IDL.Record({
  date: IDL.Text,
  slots: IDL.Vec(ServiceSlot),
});
export const Pet = IDL.Record({
  petNotes: IDL.Opt(IDL.Text),
  petName: IDL.Text,
  petType: IDL.Text,
  breed: IDL.Opt(IDL.Text),
});
export const RecurrencePattern = IDL.Variant({
  monthly: IDL.Null,
  biweekly: IDL.Null,
  weekly: IDL.Null,
});
export const TimeSlot = IDL.Record({ startTime: Time, endTime: Time });
export const DaySchedule = IDL.Record({
  date: Time,
  slots: IDL.Vec(TimeSlot),
});
export const Creation__3 = IDL.Record({
  tip: IDL.Opt(IDL.Nat),
  endDate: Time,
  serviceSchedule: IDL.Opt(IDL.Vec(DayServiceSchedule)),
  isRecurring: IDL.Bool,
  clientName: IDL.Text,
  pets: IDL.Vec(Pet),
  clientEmail: IDL.Text,
  recurrencePattern: IDL.Opt(RecurrencePattern),
  recurrenceEndDate: IDL.Opt(Time),
  notes: IDL.Text,
  clientPhone: IDL.Text,
  schedule: IDL.Opt(IDL.Vec(DaySchedule)),
  sitterIds: IDL.Vec(IDL.Nat),
  services: IDL.Vec(IDL.Text),
  startDate: Time,
});
export const BookingStatus = IDL.Variant({
  cancelled: IDL.Null,
  pending: IDL.Null,
  completed: IDL.Null,
  confirmed: IDL.Null,
});
export const Public__4 = IDL.Record({
  id: Id,
  tip: IDL.Opt(IDL.Nat),
  status: BookingStatus,
  paymentSessionId: IDL.Opt(IDL.Text),
  endDate: Time,
  serviceSchedule: IDL.Opt(IDL.Vec(DayServiceSchedule)),
  isRecurring: IDL.Bool,
  clientName: IDL.Text,
  createdAt: Time,
  pets: IDL.Vec(Pet),
  clientEmail: IDL.Text,
  recurrencePattern: IDL.Opt(RecurrencePattern),
  recurrenceEndDate: IDL.Opt(Time),
  notes: IDL.Text,
  clientPhone: IDL.Text,
  stripePaymentIntentId: IDL.Opt(IDL.Text),
  schedule: IDL.Opt(IDL.Vec(DaySchedule)),
  sitterIds: IDL.Vec(IDL.Nat),
  services: IDL.Vec(IDL.Text),
  startDate: Time,
});
export const ShoppingItem = IDL.Record({
  productName: IDL.Text,
  currency: IDL.Text,
  quantity: IDL.Nat,
  priceInCents: IDL.Nat,
  productDescription: IDL.Text,
});
export const PaymentMethod = IDL.Variant({
  stripe: IDL.Null,
  manual: IDL.Null,
});
export const PaymentSplit = IDL.Record({
  sitterId: Id,
  paid: IDL.Bool,
  amount: IDL.Nat,
});
export const Creation__2 = IDL.Record({
  method: PaymentMethod,
  bookingId: Id,
  totalAmount: IDL.Nat,
  notes: IDL.Opt(IDL.Text),
  splits: IDL.Vec(PaymentSplit),
});
export const PaymentStatus = IDL.Variant({
  pending: IDL.Null,
  paid: IDL.Null,
  refunded: IDL.Null,
});
export const Public__3 = IDL.Record({
  status: PaymentStatus,
  method: PaymentMethod,
  bookingId: Id,
  confirmedAt: IDL.Opt(Time),
  manualConfirmedBy: IDL.Opt(IDL.Principal),
  totalAmount: IDL.Nat,
  notes: IDL.Opt(IDL.Text),
  stripePaymentIntentId: IDL.Opt(IDL.Text),
  splits: IDL.Vec(PaymentSplit),
});
export const Creation__1 = IDL.Record({
  bio: IDL.Text,
  name: IDL.Text,
  hourlyRate: IDL.Nat,
  photoUrl: IDL.Text,
  location: IDL.Text,
  services: IDL.Vec(IDL.Text),
});
export const Public__1 = IDL.Record({
  service: IDL.Text,
  ratePerHour: IDL.Nat,
});
export const Public = IDL.Record({
  id: IDL.Nat,
  bio: IDL.Text,
  owner: IDL.Opt(IDL.Principal),
  name: IDL.Text,
  hourlyRate: IDL.Nat,
  photoUrl: IDL.Text,
  isActive: IDL.Bool,
  serviceRates: IDL.Vec(Public__1),
  rating: IDL.Float64,
  reviewCount: IDL.Nat,
  location: IDL.Text,
  services: IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({
  name: IDL.Text,
  role: IDL.Text,
  email: IDL.Opt(IDL.Text),
});
export const Message = IDL.Record({
  content: IDL.Text,
  timestamp: Time,
  senderName: IDL.Text,
  senderId: IDL.Opt(IDL.Principal),
});
export const ServiceStatus = IDL.Variant({
  completed: IDL.Null,
  checkedIn: IDL.Null,
  issueReported: IDL.Null,
  inProgress: IDL.Null,
});
export const Public__2 = IDL.Record({
  id: Id,
  startTime: IDL.Opt(Time),
  status: ServiceStatus,
  bookingId: Id,
  sitterId: Id,
  createdAt: Time,
  stopTime: IDL.Opt(Time),
  notes: IDL.Text,
});
export const AvailabilityEntry = IDL.Record({
  startTime: IDL.Nat,
  endTime: IDL.Nat,
  dayOfWeek: IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  completed: IDL.Record({
    userPrincipal: IDL.Opt(IDL.Text),
    response: IDL.Text,
  }),
  failed: IDL.Record({ error: IDL.Text }),
});
export const Creation = IDL.Record({
  startTime: IDL.Opt(Time),
  status: ServiceStatus,
  bookingId: Id,
  sitterId: Id,
  notes: IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  allowedCountries: IDL.Vec(IDL.Text),
  secretKey: IDL.Text,
});
export const http_header = IDL.Record({
  value: IDL.Text,
  name: IDL.Text,
});
export const http_request_result = IDL.Record({
  status: IDL.Nat,
  body: IDL.Vec(IDL.Nat8),
  headers: IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  context: IDL.Vec(IDL.Nat8),
  response: http_request_result,
});
export const TransformationOutput = IDL.Record({
  status: IDL.Nat,
  body: IDL.Vec(IDL.Nat8),
  headers: IDL.Vec(http_header),
});
export const UpdateSplits = IDL.Record({
  bookingId: Id,
  splits: IDL.Vec(PaymentSplit),
});
export const UpdateStopTime = IDL.Record({ id: Id, stopTime: Time });
export const Update = IDL.Record({
  id: Id,
  bio: IDL.Text,
  name: IDL.Text,
  hourlyRate: IDL.Nat,
  photoUrl: IDL.Text,
  isActive: IDL.Bool,
  location: IDL.Text,
  services: IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  _initializeAccessControlWithSecret: IDL.Func([IDL.Text], [], []),
  addMessage: IDL.Func([Id, IDL.Text, IDL.Text], [], []),
  assignCallerUserRole: IDL.Func([IDL.Principal, UserRole], [], []),
  claimFirstAdmin: IDL.Func([], [IDL.Bool], []),
  confirmManualPayment: IDL.Func([Id], [], []),
  createBooking: IDL.Func([Creation__3], [Public__4], []),
  createCheckoutSession: IDL.Func(
    [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
    [IDL.Text],
    [],
  ),
  createPayment: IDL.Func([Creation__2], [Public__3], []),
  createSitterProfile: IDL.Func([Creation__1], [Public], []),
  deleteSitterProfile: IDL.Func([Id], [], []),
  getActiveSitters: IDL.Func([], [IDL.Vec(Public)], ["query"]),
  getAllBookings: IDL.Func([], [IDL.Vec(Public__4)], ["query"]),
  getAllPayments: IDL.Func([], [IDL.Vec(Public__3)], ["query"]),
  getAllSitters: IDL.Func([], [IDL.Vec(Public)], ["query"]),
  getBookingsByClientEmail: IDL.Func(
    [IDL.Text],
    [IDL.Vec(Public__4)],
    ["query"],
  ),
  getBookingsBySitter: IDL.Func([Id], [IDL.Vec(Public__4)], ["query"]),
  getCallerUserProfile: IDL.Func([], [IDL.Opt(UserProfile)], ["query"]),
  getCallerUserRole: IDL.Func([], [UserRole], ["query"]),
  getMessages: IDL.Func([Id], [IDL.Vec(Message)], ["query"]),
  getPayment: IDL.Func([Id], [IDL.Opt(Public__3)], ["query"]),
  getServiceLogsByBooking: IDL.Func([Id], [IDL.Vec(Public__2)], ["query"]),
  getSitterAvailability: IDL.Func(
    [Id],
    [IDL.Vec(AvailabilityEntry)],
    ["query"],
  ),
  getSitterProfile: IDL.Func([Id], [Public], ["query"]),
  getSitterServiceRates: IDL.Func([Id], [IDL.Vec(Public__1)], ["query"]),
  getStripeSessionStatus: IDL.Func([IDL.Text], [StripeSessionStatus], []),
  getUserProfile: IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ["query"]),
  isAdminAssigned: IDL.Func([], [IDL.Bool], ["query"]),
  isCallerAdmin: IDL.Func([], [IDL.Bool], ["query"]),
  isStripeConfigured: IDL.Func([], [IDL.Bool], ["query"]),
  postServiceLog: IDL.Func([Creation], [Public__2], []),
  saveCallerUserProfile: IDL.Func([UserProfile], [], []),
  setSitterAvailability: IDL.Func([Id, IDL.Vec(AvailabilityEntry)], [], []),
  setSitterServiceRates: IDL.Func([Id, IDL.Vec(Public__1)], [], []),
  setStripeConfiguration: IDL.Func([StripeConfiguration], [], []),
  submitReview: IDL.Func([Id, IDL.Float64], [], []),
  transform: IDL.Func([TransformationInput], [TransformationOutput], ["query"]),
  updateBookingStatus: IDL.Func(
    [
      Id,
      IDL.Variant({
        cancelled: IDL.Null,
        completed: IDL.Null,
        confirmed: IDL.Null,
      }),
    ],
    [],
    [],
  ),
  updatePaymentSplits: IDL.Func([UpdateSplits], [], []),
  updateServiceLogStopTime: IDL.Func([UpdateStopTime], [], []),
  updateSitterProfile: IDL.Func([Update], [Public], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Id = IDL.Nat;
  const UserRole = IDL.Variant({
    admin: IDL.Null,
    user: IDL.Null,
    guest: IDL.Null,
  });
  const Time = IDL.Int;
  const ServiceSlot = IDL.Record({
    service: IDL.Text,
    startTime: IDL.Text,
    sitterId: IDL.Nat,
    endTime: IDL.Text,
    durationMinutes: IDL.Nat,
    ratePerHour: IDL.Nat,
  });
  const DayServiceSchedule = IDL.Record({
    date: IDL.Text,
    slots: IDL.Vec(ServiceSlot),
  });
  const Pet = IDL.Record({
    petNotes: IDL.Opt(IDL.Text),
    petName: IDL.Text,
    petType: IDL.Text,
    breed: IDL.Opt(IDL.Text),
  });
  const RecurrencePattern = IDL.Variant({
    monthly: IDL.Null,
    biweekly: IDL.Null,
    weekly: IDL.Null,
  });
  const TimeSlot = IDL.Record({ startTime: Time, endTime: Time });
  const DaySchedule = IDL.Record({
    date: Time,
    slots: IDL.Vec(TimeSlot),
  });
  const Creation__3 = IDL.Record({
    tip: IDL.Opt(IDL.Nat),
    endDate: Time,
    serviceSchedule: IDL.Opt(IDL.Vec(DayServiceSchedule)),
    isRecurring: IDL.Bool,
    clientName: IDL.Text,
    pets: IDL.Vec(Pet),
    clientEmail: IDL.Text,
    recurrencePattern: IDL.Opt(RecurrencePattern),
    recurrenceEndDate: IDL.Opt(Time),
    notes: IDL.Text,
    clientPhone: IDL.Text,
    schedule: IDL.Opt(IDL.Vec(DaySchedule)),
    sitterIds: IDL.Vec(IDL.Nat),
    services: IDL.Vec(IDL.Text),
    startDate: Time,
  });
  const BookingStatus = IDL.Variant({
    cancelled: IDL.Null,
    pending: IDL.Null,
    completed: IDL.Null,
    confirmed: IDL.Null,
  });
  const Public__4 = IDL.Record({
    id: Id,
    tip: IDL.Opt(IDL.Nat),
    status: BookingStatus,
    paymentSessionId: IDL.Opt(IDL.Text),
    endDate: Time,
    serviceSchedule: IDL.Opt(IDL.Vec(DayServiceSchedule)),
    isRecurring: IDL.Bool,
    clientName: IDL.Text,
    createdAt: Time,
    pets: IDL.Vec(Pet),
    clientEmail: IDL.Text,
    recurrencePattern: IDL.Opt(RecurrencePattern),
    recurrenceEndDate: IDL.Opt(Time),
    notes: IDL.Text,
    clientPhone: IDL.Text,
    stripePaymentIntentId: IDL.Opt(IDL.Text),
    schedule: IDL.Opt(IDL.Vec(DaySchedule)),
    sitterIds: IDL.Vec(IDL.Nat),
    services: IDL.Vec(IDL.Text),
    startDate: Time,
  });
  const ShoppingItem = IDL.Record({
    productName: IDL.Text,
    currency: IDL.Text,
    quantity: IDL.Nat,
    priceInCents: IDL.Nat,
    productDescription: IDL.Text,
  });
  const PaymentMethod = IDL.Variant({
    stripe: IDL.Null,
    manual: IDL.Null,
  });
  const PaymentSplit = IDL.Record({
    sitterId: Id,
    paid: IDL.Bool,
    amount: IDL.Nat,
  });
  const Creation__2 = IDL.Record({
    method: PaymentMethod,
    bookingId: Id,
    totalAmount: IDL.Nat,
    notes: IDL.Opt(IDL.Text),
    splits: IDL.Vec(PaymentSplit),
  });
  const PaymentStatus = IDL.Variant({
    pending: IDL.Null,
    paid: IDL.Null,
    refunded: IDL.Null,
  });
  const Public__3 = IDL.Record({
    status: PaymentStatus,
    method: PaymentMethod,
    bookingId: Id,
    confirmedAt: IDL.Opt(Time),
    manualConfirmedBy: IDL.Opt(IDL.Principal),
    totalAmount: IDL.Nat,
    notes: IDL.Opt(IDL.Text),
    stripePaymentIntentId: IDL.Opt(IDL.Text),
    splits: IDL.Vec(PaymentSplit),
  });
  const Creation__1 = IDL.Record({
    bio: IDL.Text,
    name: IDL.Text,
    hourlyRate: IDL.Nat,
    photoUrl: IDL.Text,
    location: IDL.Text,
    services: IDL.Vec(IDL.Text),
  });
  const Public__1 = IDL.Record({
    service: IDL.Text,
    ratePerHour: IDL.Nat,
  });
  const Public = IDL.Record({
    id: IDL.Nat,
    bio: IDL.Text,
    owner: IDL.Opt(IDL.Principal),
    name: IDL.Text,
    hourlyRate: IDL.Nat,
    photoUrl: IDL.Text,
    isActive: IDL.Bool,
    serviceRates: IDL.Vec(Public__1),
    rating: IDL.Float64,
    reviewCount: IDL.Nat,
    location: IDL.Text,
    services: IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({
    name: IDL.Text,
    role: IDL.Text,
    email: IDL.Opt(IDL.Text),
  });
  const Message = IDL.Record({
    content: IDL.Text,
    timestamp: Time,
    senderName: IDL.Text,
    senderId: IDL.Opt(IDL.Principal),
  });
  const ServiceStatus = IDL.Variant({
    completed: IDL.Null,
    checkedIn: IDL.Null,
    issueReported: IDL.Null,
    inProgress: IDL.Null,
  });
  const Public__2 = IDL.Record({
    id: Id,
    startTime: IDL.Opt(Time),
    status: ServiceStatus,
    bookingId: Id,
    sitterId: Id,
    createdAt: Time,
    stopTime: IDL.Opt(Time),
    notes: IDL.Text,
  });
  const AvailabilityEntry = IDL.Record({
    startTime: IDL.Nat,
    endTime: IDL.Nat,
    dayOfWeek: IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    completed: IDL.Record({
      userPrincipal: IDL.Opt(IDL.Text),
      response: IDL.Text,
    }),
    failed: IDL.Record({ error: IDL.Text }),
  });
  const Creation = IDL.Record({
    startTime: IDL.Opt(Time),
    status: ServiceStatus,
    bookingId: Id,
    sitterId: Id,
    notes: IDL.Text,
  });
  const StripeConfiguration = IDL.Record({
    allowedCountries: IDL.Vec(IDL.Text),
    secretKey: IDL.Text,
  });
  const http_header = IDL.Record({ value: IDL.Text, name: IDL.Text });
  const http_request_result = IDL.Record({
    status: IDL.Nat,
    body: IDL.Vec(IDL.Nat8),
    headers: IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    context: IDL.Vec(IDL.Nat8),
    response: http_request_result,
  });
  const TransformationOutput = IDL.Record({
    status: IDL.Nat,
    body: IDL.Vec(IDL.Nat8),
    headers: IDL.Vec(http_header),
  });
  const UpdateSplits = IDL.Record({
    bookingId: Id,
    splits: IDL.Vec(PaymentSplit),
  });
  const UpdateStopTime = IDL.Record({ id: Id, stopTime: Time });
  const Update = IDL.Record({
    id: Id,
    bio: IDL.Text,
    name: IDL.Text,
    hourlyRate: IDL.Nat,
    photoUrl: IDL.Text,
    isActive: IDL.Bool,
    location: IDL.Text,
    services: IDL.Vec(IDL.Text),
  });

  return IDL.Service({
    _initializeAccessControlWithSecret: IDL.Func([IDL.Text], [], []),
    addMessage: IDL.Func([Id, IDL.Text, IDL.Text], [], []),
    assignCallerUserRole: IDL.Func([IDL.Principal, UserRole], [], []),
    claimFirstAdmin: IDL.Func([], [IDL.Bool], []),
    confirmManualPayment: IDL.Func([Id], [], []),
    createBooking: IDL.Func([Creation__3], [Public__4], []),
    createCheckoutSession: IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
    createPayment: IDL.Func([Creation__2], [Public__3], []),
    createSitterProfile: IDL.Func([Creation__1], [Public], []),
    deleteSitterProfile: IDL.Func([Id], [], []),
    getActiveSitters: IDL.Func([], [IDL.Vec(Public)], ["query"]),
    getAllBookings: IDL.Func([], [IDL.Vec(Public__4)], ["query"]),
    getAllPayments: IDL.Func([], [IDL.Vec(Public__3)], ["query"]),
    getAllSitters: IDL.Func([], [IDL.Vec(Public)], ["query"]),
    getBookingsByClientEmail: IDL.Func(
      [IDL.Text],
      [IDL.Vec(Public__4)],
      ["query"],
    ),
    getBookingsBySitter: IDL.Func([Id], [IDL.Vec(Public__4)], ["query"]),
    getCallerUserProfile: IDL.Func([], [IDL.Opt(UserProfile)], ["query"]),
    getCallerUserRole: IDL.Func([], [UserRole], ["query"]),
    getMessages: IDL.Func([Id], [IDL.Vec(Message)], ["query"]),
    getPayment: IDL.Func([Id], [IDL.Opt(Public__3)], ["query"]),
    getServiceLogsByBooking: IDL.Func([Id], [IDL.Vec(Public__2)], ["query"]),
    getSitterAvailability: IDL.Func(
      [Id],
      [IDL.Vec(AvailabilityEntry)],
      ["query"],
    ),
    getSitterProfile: IDL.Func([Id], [Public], ["query"]),
    getSitterServiceRates: IDL.Func([Id], [IDL.Vec(Public__1)], ["query"]),
    getStripeSessionStatus: IDL.Func([IDL.Text], [StripeSessionStatus], []),
    getUserProfile: IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ["query"],
    ),
    isAdminAssigned: IDL.Func([], [IDL.Bool], ["query"]),
    isCallerAdmin: IDL.Func([], [IDL.Bool], ["query"]),
    isStripeConfigured: IDL.Func([], [IDL.Bool], ["query"]),
    postServiceLog: IDL.Func([Creation], [Public__2], []),
    saveCallerUserProfile: IDL.Func([UserProfile], [], []),
    setSitterAvailability: IDL.Func([Id, IDL.Vec(AvailabilityEntry)], [], []),
    setSitterServiceRates: IDL.Func([Id, IDL.Vec(Public__1)], [], []),
    setStripeConfiguration: IDL.Func([StripeConfiguration], [], []),
    submitReview: IDL.Func([Id, IDL.Float64], [], []),
    transform: IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ["query"],
    ),
    updateBookingStatus: IDL.Func(
      [
        Id,
        IDL.Variant({
          cancelled: IDL.Null,
          completed: IDL.Null,
          confirmed: IDL.Null,
        }),
      ],
      [],
      [],
    ),
    updatePaymentSplits: IDL.Func([UpdateSplits], [], []),
    updateServiceLogStopTime: IDL.Func([UpdateStopTime], [], []),
    updateSitterProfile: IDL.Func([Update], [Public], []),
  });
};

export const init = ({ IDL }) => {
  return [];
};
